{
 "title": "Comparaison RSSI & Errors & Time Deltas",
 "tags": [ "diagnostique" ],
 "time": { "from": "now-3M", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n    bucket: \"potager-bucket\",\n    tag: \"location\",\n    measurement: \"jardin-pa-bakken\",\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"potager-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"rssi\"\n  )\n  |> filter(fn: (r) =>\n    r.location =~ /${location:regex}/\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  { "gridPos": { "h": 9, "w": 4, "x": 19, "y": 0 } },
  {
   "title": "Error ACK & CCA",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"potager-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"error_ack\"\n  )|> filter(fn: (r) =>\n    r.location =~ /${location:regex}/\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)"
    },
    {
     "query": "from(bucket: \"potager-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"error_cca\"\n  )\n  |> filter(fn: (r) =>\n    r.location =~ /${location:regex}/\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)"
    }
   ]
  },
  {
   "title": "Time delta",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"potager-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"temp\"\n  )\n  |> filter(fn: (r) =>\n    r.location =~ /${location:regex}/\n  )\n  |> elapsed(unit: 1ms)\n  |> drop(columns: [\"_value\"])\n  |> map(fn: (r) => ({r with elapsed: r.elapsed - 900000}))\n  |> aggregateWindow(column: \"elapsed\", every: v.windowPeriod, fn: mean)"
    }
   ]
  }
 ]
}