{
 "title": "Derniers 30 jours par Lieux",
 "tags": [ "journalier" ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n    bucket: \"potager-bucket\",\n    tag: \"location\",\n    measurement: \"jardin-pa-bakken\",\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Température Min/Moyenne/Max par jour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"potager-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"temp\" and\n    r.location == \"${location}\"\n  )\n  |> aggregateWindow(every: 1d, fn: mean)\n  |> rename(columns: {_value: \"mean\"})\n  \n  "
    },
    {
     "query": "from(bucket: \"potager-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"temp\" and\n    r.location == \"${location}\"\n  )\n  |> aggregateWindow(every: 1d, fn: min)\n  |> rename(columns: {_value: \"min\"})\n  "
    },
    {
     "query": "from(bucket: \"potager-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"temp\" and\n    r.location == \"${location}\"\n  )\n  |> aggregateWindow(every: 1d, fn: max)\n  |> rename(columns: {_value: \"max\"})\n  "
    }
   ]
  },
  {
   "title": "Lumière Mean/Max par jour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "from(bucket: \"potager-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"light\" and\n    r.location == \"${location}\"\n  )\n  |> aggregateWindow(every: 1d, fn: mean)\n  |> rename(columns: {_value: \"mean\"})\n  \n  "
    },
    {
     "query": "from(bucket: \"potager-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"light\" and\n    r.location == \"${location}\"\n  )\n  |> aggregateWindow(every: 1d, fn: max)\n  |> rename(columns: {_value: \"max\"})\n  "
    }
   ]
  },
  {
   "title": "Humidité Max Journalière",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"potager-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"moist\" and\n    r.location == \"${location}\"\n  )\n  |> aggregateWindow(every: 1d, fn: max)\n  "
    }
   ]
  }
 ]
}