{
 "title": "Diagnostique par sonde",
 "time": { "from": "now-3M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n    bucket: \"gr-bucket\",\n    tag: \"location\",\n    measurement: \"jardin-pa-bakken\",\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "Battery vs Xbee Supply",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\"\n    and (r._field == \"batt\" or r._field == \"v_supply\")\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> filter(fn: (r) => r.location == \"${location}\")\n  |> toFloat()\n  |> map(fn: (r) => ({\n    r with _value: \n    if r._field == \"v_supply\" \n    then r._value / 1000.0\n    else r._value\n  }))"
    }
   ]
  },
  { "gridPos": { "h": 3, "w": 5, "x": 13, "y": 0 } },
  { "gridPos": { "h": 6, "w": 2, "x": 18, "y": 0 } },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"rssi\"\n  )\n  |> filter(fn: (r) => r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Errors ACK",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"error_ack\"\n  )\n  |> filter(fn: (r) => r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)"
    }
   ]
  },
  {
   "title": "Errors CCA",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"error_cca\"\n  )\n  |> filter(fn: (r) => r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)"
    }
   ]
  }
 ]
}