{
 "title": "Diagnostique par sonde",
 "tags": [ "diagnostique" ],
 "time": { "from": "now-3M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n    bucket: \"gr-bucket\",\n    tag: \"location\",\n    measurement: \"jardin-pa-bakken\",\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop\n)"
   }
  ]
 },
 "panels": [
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Battery vs Xbee Supply",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\"\n    and (r._field == \"batt\" or r._field == \"v_supply\")\n  )\n  |> filter(fn: (r) => r.location == \"${location}\")\n  |> toFloat()\n  |> map(fn: (r) => ({\n    r with _value: \n    if r._field == \"v_supply\" \n    then r._value / 1000.0\n    else r._value\n  }))\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  { "gridPos": { "h": 3, "w": 5, "x": 13, "y": 1 } },
  { "gridPos": { "h": 6, "w": 2, "x": 18, "y": 1 } },
  { "title": "Signal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"rssi\"\n  )\n  |> filter(fn: (r) => r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Errors ACK & CCA",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"error_ack\" or r._field == \"error_cca\"\n  )\n  |> filter(fn: (r) => r.location == \"${location}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)"
    }
   ]
  },
  { "title": "Time delta", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Time delta",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"temp\"\n  )\n  |> filter(fn: (r) => r.location == \"${location}\")\n  |> elapsed(unit: 1s)\n  |> drop(columns: [\"_value\"])\n  |> map(fn: (r) => ({r with elapsed: r.elapsed - 900}))\n  |> aggregateWindow(column: \"elapsed\", every: v.windowPeriod, fn: max)"
    }
   ]
  },
  {
   "title": "Time delta close up",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"temp\"\n  )\n  |> filter(fn: (r) => r.location == \"${location}\")\n  |> elapsed(unit: 1ms)\n  |> drop(columns: [\"_value\"])\n  |> map(fn: (r) => ({r with elapsed: r.elapsed - 900000}))\n  |> aggregateWindow(column: \"elapsed\", every: v.windowPeriod, fn: mean)"
    }
   ]
  }
 ]
}