{
 "title": "Groupe sélection",
 "time": { "from": "now-5d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "probe_id",
    "query": "potager sud : 5526146545295748, noisetier : 5526146547246824"
   }
  ]
 },
 "panels": [
  {
   "title": "Température moyenne",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"temp\" and\n    r.probe_id =~ /${probe_id:regex}/\n  )\n  |>last()\n  |>group()"
    }
   ]
  },
  {
   "title": "Température",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"temp\"\n  )\n  |> filter(fn: (r) =>\n    r.probe_id =~ /${probe_id:regex}/\n  )"
    }
   ]
  },
  {
   "title": "Last update",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"strings\"\n\nfrom(bucket: \"gr-bucket\")\n  |> range(start: -30d)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"batt\"\n  )\n  |> filter(fn: (r) =>\n    r.probe_id =~ /${probe_id:regex}/\n  )\n  |>last()\n  |> map(fn: (r) => ({r with _value: uint(v: date.truncate(t: now(), unit: 1m)) - uint(v: date.truncate(t: r._time, unit: 1m))}))\n  // nanosec to minutes\n  |> toFloat()\n  |> map(fn: (r) => ({r with _value: r._value / 60000000000.0}))\n"
    }
   ]
  },
  {
   "title": "Lumière moyenne",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"light\" and\n    r.probe_id =~ /${probe_id:regex}/\n  )\n  |>last()\n  |>group()"
    }
   ]
  },
  {
   "title": "Lumière",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"light\"\n  )\n  |> filter(fn: (r) =>\n    r.probe_id =~ /${probe_id:regex}/\n  )"
    }
   ]
  },
  {
   "title": "Humidité moyenne",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"moist\" and\n    r.probe_id =~ /${probe_id:regex}/\n  )\n  |>last()\n  |>group()"
    }
   ]
  },
  {
   "title": "Humidité du sol",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"moist\"\n  )\n  |> filter(fn: (r) =>\n    r.probe_id =~ /${probe_id:regex}/\n  )"
    }
   ]
  }
 ]
}