{
 "title": "RSSI & Errors",
 "time": { "from": "now-3M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurementTagValues(\n    bucket: \"gr-bucket\",\n    tag: \"location\",\n    measurement: \"jardin-pa-bakken\",\n    start: v.timeRangeStart,\n    stop: v.timeRangeStop\n)"
   }
  ]
 },
 "panels": [
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"rssi\"\n  )\n  |> filter(fn: (r) =>\n    r.location =~ /${location:regex}/\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  { "gridPos": { "h": 6, "w": 4, "x": 19, "y": 0 } },
  {
   "title": "Error ACK",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"error_ack\"\n  )|> filter(fn: (r) =>\n    r.location =~ /${location:regex}/\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)"
    }
   ]
  },
  {
   "title": "Error CCA",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"jardin-pa-bakken\" and\n    r._field == \"error_cca\"\n  )\n  |> filter(fn: (r) =>\n    r.location =~ /${location:regex}/\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: sum)"
    }
   ]
  }
 ]
}