{
 "title": "Une par une",
 "time": { "from": "now-5d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "probe_id",
    "query": "potager sud : \"5526146545295748\", noisetier : \"5526146547246824\""
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"temp\" and\n    r.probe_id == ${probe_id}\n  )\n  "
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"temp\" and\n    r.probe_id == ${probe_id}\n  )"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"rssi\" and\n    r.probe_id == ${probe_id}\n  )"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 2, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"batt\" and\n    r.probe_id == ${probe_id}\n  )"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"strings\"\n\nfrom(bucket: \"gr-bucket\")\n  |> range(start: -30d)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"batt\" and\n    r.probe_id == ${probe_id}\n  )\n  |>last()\n  |> map(fn: (r) => ({_value: uint(v: date.truncate(t: now(), unit: 1m)) - uint(v: date.truncate(t: r._time, unit: 1m))}))\n  |> map(fn: (r) => ({_value: string(v: duration(v: r._value))}))\n"
    }
   ]
  },
  {
   "title": "Light",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"light\" and\n    r.probe_id == ${probe_id}\n  )"
    }
   ]
  },
  {
   "title": "Light",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"light\" and\n    r.probe_id == ${probe_id}\n  )\n  "
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"error_ack\" and\n    r.probe_id == ${probe_id}\n  )"
    }
   ]
  },
  {
   "title": "Soil Moisture",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"moist\" and\n    r.probe_id == ${probe_id}\n  )"
    }
   ]
  },
  {
   "title": "Soil Moisture",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"gr-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"proto4\" and\n    r._field == \"moist\" and\n    r.probe_id == ${probe_id}\n  )"
    }
   ]
  }
 ]
}