{
 "title": "Water Diagnostic",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Daily Water Usage",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "import \"timezone\"\noption location = timezone.location(name: \"Europe/Paris\")\n\nfrom(bucket: \"potager-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"water-web-control\" and\n    r._field == \"water\"\n  )\n  |> aggregateWindow(every: 1d, timeSrc: \"_start\", fn: sum)\n"
    }
   ]
  },
  {
   "title": "Water usage - last 24h close up",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    {
     "query": "import \"timezone\"\noption location = timezone.location(name: \"Europe/Paris\")\n\nfrom(bucket: \"potager-bucket\")\n  |> range(start: -24h)\n  |> filter(fn: (r) =>\n    r._measurement == \"water-web-control\" and\n    r._field == \"water\"\n  )\n |> aggregateWindow(every: 1h, fn: sum, createEmpty: false, timeSrc: \"_start\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"timezone\"\noption location = timezone.location(name: \"Europe/Paris\")\n\nfrom(bucket: \"potager-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"water-web-control\" and\n    r._field == \"temp\"\n  )\n  |> aggregateWindow(every: w.windowPeriod, timeSrc: \"_start\", fn: mean)\n"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "query": "import \"timezone\"\noption location = timezone.location(name: \"Europe/Paris\")\n\nfrom(bucket: \"potager-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"water-web-control\" and\n    r._field == \"rssi\"\n  )\n  |> aggregateWindow(every: w.windowPeriod, timeSrc: \"_start\", fn: mean)\n"
    }
   ]
  }
 ]
}